version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.4
    ports:
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://clickhouse:8123/ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - clickhouse
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:clickhouse://clickhouse:8123/default?send_retries=3&retry_delay=1000&socket_timeout=30000&tcp_keep_alive=true
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.clickhouse.jdbc.ClickHouseDriver

volumes:
  clickhouse-data: